name: Mathematics for ML's Blog
url: 'https://mathematics-for-ml.github.io/MIT-18.065-Linear-Algebra/'
description: 'Study notes'

exclude: [Gemfile, Gemfile.lock, README.md]

author: 'Mathematics for ML'
mathjax: true # whether support mathjax

future: true

kramdown:
  input: GFM
  math_engine: mathjax

# gems:
#   # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
#   - jekyll-gist
#   - jekyll-sitemap

# sitemap:
#     filename: "/sitemap.xml"
#     exclude:
#         - "/atom.xml"
#         - "/feed.xml"
#         - "/feed/index.xml"
#     include_posts:
#         - "/index.html"
#     change_frequency_name: "change_frequency"
#     priority_name: "priority"


gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-toc



sass:
    sass_dir: _sass
    style: :compressed
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-toc
